FROM eclipse-temurin:17-jre

ENV EULA=TRUE
ENV VERSION={{ version }}

WORKDIR /data

RUN curl -L -o server.jar https://meta.fabricmc.net/v2/versions/loader/${VERSION}/latest/server/jar

VOLUME ["/data"]

EXPOSE 25565

CMD ["java", "-Xms1G", "-Xmx1G", "-jar", "server.jar", "nogui"]
